version: '3'
volumes: 
    dados:
services: 
    db:
        image: postgres
        environment:
            POSTGRES_DB: "docker"
            POSTGRES_USER: "docker"
            POSTGRES_PASSWORD: "password"
        ports: 
             - 5432:5432
        volumes:
            # Volume dos dados 
            - dados:/var/lib/postgresql/data


